import { Inter } from "next/font/google"
import PageLayout from "@/components/Auth/PageLayout"
import Head from "next/head"
import { useEffect, useState } from "react"
import NoInternetConnection from "@/components/Network/Network"
import { useRouter } from "next/router"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const router = useRouter()
  const [isOnline, setIsOnline] = useState(
    typeof window !== "undefined" ? navigator.onLine : true
  )

  useEffect(() => {
    router.replace("/login")
  }, [router])

  useEffect(() => {
    const handleOnline = () => {
      setIsOnline(true)
    }

    const handleOffline = () => {
      setIsOnline(false)
    }

    window.addEventListener("online", handleOnline)
    window.addEventListener("offline", handleOffline)

    return () => {
      window.removeEventListener("online", handleOnline)
      window.removeEventListener("offline", handleOffline)
    }
  })

  return (
    <>
      <Head>
        <title>Kemsey Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen bg-white w-full flex-col items-center justify-between ${inter.className}`}
      >
        {isOnline ? <PageLayout /> : <NoInternetConnection />}
      </main>
    </>
  )
}
